definitions:
  model.AddUser:
    properties:
      age:
        type: integer
      name:
        type: string
    required:
    - age
    - name
    type: object
  model.RegisterBody:
    properties:
      login:
        type: string
      password:
        type: string
    type: object
  model.RegisterResponse:
    properties:
      account_id:
        type: integer
    type: object
  model.SignInBody:
    properties:
      login:
        type: string
      password:
        type: string
    type: object
  model.SignInResponse:
    properties:
      token:
        type: string
    type: object
  model.UpdateUserSwagger:
    properties:
      age:
        type: integer
      name:
        type: string
    type: object
  model.User:
    properties:
      age:
        type: integer
      id:
        type: integer
      name:
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  description: This is an API server for working with users
  title: Users API
  version: "1.0"
paths:
  /api/v1/admins/:
    get:
      consumes:
      - application/json
      description: Retrieves admin status and greets the admin or informs if the user
        is not an admin.
      produces:
      - application/json
      responses:
        "200":
          description: Greeting message
          schema:
            type: string
        "500":
          description: Something went wrong.
          schema:
            type: string
      security:
      - ApiKeyAuth: []
      summary: Get admin information
      tags:
      - Admin
  /api/v1/auth/login:
    post:
      consumes:
      - application/json
      description: Authenticate user and return a JWT token
      parameters:
      - description: User login and password
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/model.SignInBody'
      produces:
      - application/json
      responses:
        "200":
          description: token
          schema:
            $ref: '#/definitions/model.SignInResponse'
        "400":
          description: incorrect request structure
          schema:
            type: string
        "500":
          description: couldn't create the token
          schema:
            type: string
      summary: Sign in user
      tags:
      - auth
  /api/v1/auth/register:
    post:
      consumes:
      - application/json
      description: Create a new user account and return the user ID
      parameters:
      - description: User login and password
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/model.RegisterBody'
      produces:
      - application/json
      responses:
        "200":
          description: account id
          schema:
            $ref: '#/definitions/model.RegisterResponse'
        "400":
          description: incorrect request structure
          schema:
            type: string
        "500":
          description: couldn't create the user
          schema:
            type: string
      summary: Register a new user
      tags:
      - auth
  /api/v1/users/:
    get:
      description: Retrieve a list of users with optional filters.
      parameters:
      - description: Page number
        in: query
        name: page
        type: integer
      - description: Number of users per page
        in: query
        name: limit
        type: integer
      - description: Filter by age
        in: query
        name: age
        type: integer
      - description: Filter by name
        in: query
        name: name
        type: string
      responses:
        "200":
          description: List of users
          schema:
            items:
              $ref: '#/definitions/model.User'
            type: array
        "400":
          description: Invalid query parameters
          schema:
            type: string
        "500":
          description: Internal server error
          schema:
            type: string
      security:
      - ApiKeyAuth: []
      summary: Get users
      tags:
      - songs
    post:
      description: This function accepts a JSON object of the user and adds it to
        the system.
      parameters:
      - description: User data
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/model.AddUser'
      responses:
        "200":
          description: ID of the added user
          schema:
            type: integer
        "400":
          description: Incorrect fields in request
          schema:
            type: string
        "500":
          description: Internal server error
          schema:
            type: string
      summary: Add a new user
      tags:
      - songs
  /api/v1/users/{id}:
    delete:
      description: This function deletes a user based on the provided ID.
      parameters:
      - description: User ID
        in: path
        name: id
        required: true
        type: integer
      responses:
        "200":
          description: Indicates if the user was successfully deleted
          schema:
            type: boolean
        "400":
          description: Invalid user ID
          schema:
            type: string
        "500":
          description: Internal server error
          schema:
            type: string
      summary: Delete an existing user
      tags:
      - songs
    get:
      description: Retrieve a user based on the provided user ID.
      parameters:
      - description: User ID
        in: path
        name: id
        required: true
        type: integer
      responses:
        "200":
          description: User details
          schema:
            $ref: '#/definitions/model.User'
        "400":
          description: Invalid user ID
          schema:
            type: string
        "500":
          description: Internal server error
          schema:
            type: string
      summary: Get user by ID
      tags:
      - songs
    put:
      description: This function updates user information based on the provided ID
        and data.
      parameters:
      - description: User ID
        in: path
        name: id
        required: true
        type: integer
      - description: Updated user data
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/model.UpdateUserSwagger'
      responses:
        "200":
          description: Updated user information
          schema:
            $ref: '#/definitions/model.User'
        "400":
          description: Incorrect fields or invalid user ID
          schema:
            type: string
        "500":
          description: Internal server error
          schema:
            type: string
      summary: Update an existing user
      tags:
      - songs
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
